import { getOriginalURL } from '../utils';

export const APP_CONSTANTS = {
  EXTENSION_NAME: 'INCOGNITO_EXTENSION'
};

export const SEND_ACTIONS_NAME = {
  REQUEST_CONNECT_ACCOUNT: 'BACKGROUND_REQUEST_CONNECT_ACCOUNT',
  CHECK_CONNECT_ACCOUNT: 'BACKGROUND_CHECK_CONNECT_ACCOUNT',
  REQUEST_SEND_TX: 'BACKGROUND_REQUEST_SEND_TX',
};

export const RECEIVE_ACTIONS_NAME = {
  ACTION_KEY: APP_CONSTANTS.EXTENSION_NAME + '|' + getOriginalURL(),
  CONNECT_TO_ACCOUNT_SUCCESS: 'CONTENT_CONNECT_TO_ACCOUNT_SUCCESS',
  DISCONNECT_ACCOUNT: 'CONTENT_DISCONNECT_ACCOUNT',
  SEND_TX_FINISH: 'CONTENT_SEND_TX_FINISH',
  CANCEL_SEND_TX: 'CONTENT_CANCEL_SEND_TX'
};