import SDK from 'incognito-extension-sdk';

const EXTENSION_CONSTANTS = SDK.RECEIVE_ACTIONS_NAME;

const EXTENSION_EVENT = {
    CONNECT_TO_ACCOUNT_SUCCESS: EXTENSION_CONSTANTS.CONNECT_TO_ACCOUNT_SUCCESS,
    CONNECT_TO_ACCOUNT_ERROR: EXTENSION_CONSTANTS.CONNECT_TO_ACCOUNT_ERROR,
    DISCONNECT_ACCOUNT: EXTENSION_CONSTANTS.DISCONNECT_ACCOUNT,
    SEND_TX_FINISH: EXTENSION_CONSTANTS.SEND_TX_FINISH,
    CANCEL_SEND_TX: EXTENSION_CONSTANTS.CANCEL_SEND_TX,
}

export default EXTENSION_EVENT;